### ISSUE TITLE
Add something like -g, --grep <pattern> on mocha

### ISSUE THREAD

**Issue by camilosw** [arunoda/laika#52]
I doesn't found any option to set the suite I want to run. Laika always run all the suites.

**Comment by arunoda** [comment]
You can limit laika to run a single file/folder with

laika [options] tests/file.js

Anyway -g should be easy to add since laika using mocha. Patches are
welcome :)

On Mon, Aug 19, 2013 at 2:22 AM, Camilo notifications@github.com wrote:

> I doesn't found any option to set the suite I want to run. Laika always
> run all the suites.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/52
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
This is now enabled with the new version `0.3.0`
