### ISSUE TITLE
Integrating nightwatch.js

### ISSUE THREAD

**Issue by wbashir** [arunoda/laika#80]
Would there be a conflict if we tried to use another testing framework with laika like this one http://nightwatchjs.org/

**Comment by arunoda** [comment]
I'm not exactly sure how it works. Since it's based on selenium, I don't
think their won't be any conflict.

But I'm not sure, how you can use them inside Laika.

On Fri, Jan 31, 2014 at 8:31 PM, warsamebashir notifications@github.comwrote:

> Would there be a conflict if we tried to use another testing framework
> with laika like this one http://nightwatchjs.org/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/80
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by wbashir** [comment]
thanks, i am playing around with it now with no real issues yet.

**Comment by arunoda** [comment]
Nice to hear that.

On Sun, Feb 2, 2014 at 12:54 AM, warsamebashir notifications@github.comwrote:

> Closed #80 https://github.com/arunoda/laika/issues/80.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/80
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
