### ISSUE TITLE
Weird API

### ISSUE THREAD

**Issue by srounce** [arunoda/laika#9]
First, great work. I'm really looking forward to using Laika!

However, first thing that struck me as soon as I read the docs was the fugly naming conventions of pretty much the whole API. Things such as 'ltest' and 'emit'/'once'/'on' doesn't seem very intuitive. Couldn't 'ltest' just be 'laika'. The value of _laika_ would depend on the test style (tdd/bdd/etc.)

As for things such as 'eval' and 'evalSync'; well, it's just downright confusing. Seeing as 'eval' is commonly used to name functions that evaluate expressions in string values, not running a function. Not just in JS but in a whole bucketload of languages. Surely this should be something such as _'run'_ / 'runSync' seeing as we are _running_ a test.

Thoughts?

**Comment by timhaines** [comment]
I found some friction with the naming too..

**Comment by srounce** [comment]
Suggestions?

**Comment by arunoda** [comment]
thanks for the interest in laika.

Yes. `ltest` is a really bad name. I wish I could use `test` but it clouldn't. `laika` is a pretty good alternative.

`emit/once/on` these are derived from the EventEmitter in nodejs and it does the exact functionality.

I prefer using `eval` instead in `run` since we actually evaluating a string at the end. And you won't have the closure support in the  `eval` too.

**Comment by srounce** [comment]
@arunoda Define, 'evaluating a string'.

**Comment by arunoda** [comment]
see: http://goo.gl/Eamme

On Fri, Jun 7, 2013 at 12:40 PM, Samuel Rounce notifications@github.comwrote:

> @arunoda https://github.com/arunoda Define, 'evaluating a string'.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/9#issuecomment-19092278
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
And try to see [concept section](http://arunoda.github.io/laika/concepts.html) for how we do this internally.

**Comment by srounce** [comment]
I fully understand this, however, `eval` takes a `Function` as it's argument, no? How it's handled internally means sweet F.A. to the end user.

**Comment by arunoda** [comment]
I got your point my friend :)
But I prefer to name it has eval since I'm evaluating stringified version
of the function in the server and the client.

Internally in the server I use JS eval function - http://goo.gl/qr4X8
And for the client I use phantomJs's .evaluate() - http://goo.gl/Efa8q

And I'll consider making `ltest` into `laika` in the previous versions.
Need to find out how others think about it.

On Fri, Jun 7, 2013 at 12:44 PM, Samuel Rounce notifications@github.comwrote:

> I fully understand this, however, the eval function itself takes a
> Function as it's argument, no?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/issues/9#issuecomment-19092405
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by malkomalko** [comment]
I'm a big fan of facts/fact:

```
facts("about posting", function(){
  fact("it does not allow weird chars", function(){..}
})
```

**Comment by arunoda** [comment]
Nice. any place where this is used? any testing framework

**Comment by malkomalko** [comment]
https://github.com/josephwilk/amrita
https://github.com/marick/Midje

**Comment by srounce** [comment]
+1 on the use of _facts_. Semantically, it seems appropriate.

**Comment by malkomalko** [comment]
also I don't like .eval either... I'd much rather have .run for client/server.  you even say yourself in the free screencast "In order to run code on the server", so semantically I think it makes much more sense.

**Comment by arunoda** [comment]
I've marked `ltest` as deprecated and you can use `test` instead now. (with laika version `0.1.22`)

`facts` style is good, I like it, unfortunately `mocha` does not support it. 

`eval` and `evalSync` won't get changed. sorry for that.
